#!/usr/bin/env python3
import argparse
import json
from pathlib import Path

import tiktoken


def count_tokens(text: str, encoding_name: str) -> int:
    enc = tiktoken.get_encoding(encoding_name)
    return len(enc.encode(text))


def compact_json(value) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def percentile(values, pct):
    if not values:
        return 0
    sorted_vals = sorted(values)
    idx = int((len(sorted_vals) - 1) * pct / 100)
    return sorted_vals[idx]


def main():
    parser = argparse.ArgumentParser(description="Measure MCP tool payload token usage.")
    parser.add_argument(
        "--input",
        default=".tmp_tools_list.json",
        help="Path to tools JSON generated by dump-mcp-tools.js",
    )
    parser.add_argument(
        "--out",
        default=".tmp_tool_token_metrics.json",
        help="Path to write metrics JSON",
    )
    args = parser.parse_args()

    input_path = Path(args.input).resolve()
    out_path = Path(args.out).resolve()
    payload = json.loads(input_path.read_text(encoding="utf-8"))

    tools = payload.get("tools", payload)
    if not isinstance(tools, list):
        raise SystemExit("Input JSON does not contain a tools list.")

    full_payload = {"tools": tools}
    essential_payload = [
        {
            "name": t.get("name"),
            "description": t.get("description"),
            "inputSchema": t.get("inputSchema"),
        }
        for t in tools
    ]

    full_json = compact_json(full_payload)
    essential_json = compact_json({"tools": essential_payload})

    tool_token_sizes_o200k = [count_tokens(compact_json(t), "o200k_base") for t in tools]
    tool_token_sizes_cl100k = [count_tokens(compact_json(t), "cl100k_base") for t in tools]

    metrics = {
        "input_file": str(input_path),
        "tool_count": len(tools),
        "chars": {
            "full_payload_json": len(full_json),
            "essential_payload_json": len(essential_json),
        },
        "tokens": {
            "o200k_base": {
                "full_payload": count_tokens(full_json, "o200k_base"),
                "essential_payload": count_tokens(essential_json, "o200k_base"),
                "per_tool_avg": round(
                    sum(tool_token_sizes_o200k) / len(tool_token_sizes_o200k), 2
                )
                if tool_token_sizes_o200k
                else 0,
                "per_tool_p50": percentile(tool_token_sizes_o200k, 50),
                "per_tool_p95": percentile(tool_token_sizes_o200k, 95),
                "largest_single_tool": max(tool_token_sizes_o200k) if tool_token_sizes_o200k else 0,
            },
            "cl100k_base": {
                "full_payload": count_tokens(full_json, "cl100k_base"),
                "essential_payload": count_tokens(essential_json, "cl100k_base"),
                "per_tool_avg": round(
                    sum(tool_token_sizes_cl100k) / len(tool_token_sizes_cl100k), 2
                )
                if tool_token_sizes_cl100k
                else 0,
                "per_tool_p50": percentile(tool_token_sizes_cl100k, 50),
                "per_tool_p95": percentile(tool_token_sizes_cl100k, 95),
                "largest_single_tool": max(tool_token_sizes_cl100k) if tool_token_sizes_cl100k else 0,
            },
        },
    }

    out_path.write_text(json.dumps(metrics, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(metrics, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()

